# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

elk:
  build: .
  ports:
    - "5601:5601"
    - "9200"
    - "5046:5046"
  volumes:
    - /home/jaci/tmp/elk-data:/var/lib/elasticsearch
